source 'https://rubygems.org'
gem "middleman"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-imageoptim"
gem "middleman-inliner"
gem "middleman-s3_sync", :github => "fredjean/middleman-s3_sync", :ref => "92cff50b8a8bf28d90f7b841a08e019c276de5cd"
gem "middleman-s3_redirect", :github => "fredjean/middleman-s3_redirect", :ref => "97e33c14f696e555e1958a941d3f1dd6e701c72b"
gem "middleman-favicon-maker"
gem "middleman-autoprefixer"
gem "filecache"
gem "sanitize"
gem "builder"
gem "parallel"
gem "nokogiri"
gem "pry-byebug"
gem "httparty"
